### ISSUE TITLE
Fulfill the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/apns4erl#29]
## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's hooked to a hipchat room
- [x] It's has a clear and useful README.md
- [x] It's documented (with examples)
- [x] It's tested
## Exhibition
- [ ] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description
- [x] It has a landing page built in github pages
## For Libraries
- [x] Examples of use are documented in the README or linked from there
## For Erlang Projects
- [x] It's checked with [Elvis](http://github.com/inaka/elvis)
